package metro;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author mohit dawar
 */
public class MetroHome extends javax.swing.JFrame {

    /**
     * Creates new form MetroCollege
     */
    
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
	
	public MetroHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("~~~~~~~~~~   DELHI METRO RAILWAY CORPORATION ~~~~~~~~~");

        jLabel3.setText("  Please   provide  the  stations  !!");

        jLabel4.setText("  Current  Station");

        jLabel5.setText("  Destination Station");

        jLabel6.setText("  No of stations");

        jLabel7.setText("  Total Fare");

        jButton1.setText("see map");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMapAction(evt);
            }
        });

        jButton2.setText("alternate route");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternateRouteAction(evt);
            }
        });

        jLabel8.setText("~~~~~~~~~~ Here you get your route information ~~~~~~~~~~~~ ");

        jButton3.setText("calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateAction(evt);
            }
        });

        jButton4.setText("reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
										.addComponent(jTextField1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20)
                .addComponent(jButton4))
        );

        pack();
    }

    private void seeMapAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cs=jTextField1.getText();
        String ds=jTextField2.getText();
        int cs_id=0;
        int d_id=0;
//        Configuration cfg=new Configuration();
//        cfg.configure("hibernate.cfg.xml");
//        SessionFactory sf=cfg.buildSessionFactory();
//        Session s=sf.openSession();
//        Query q=s.createQuery("select s from MiniPojo s where s.station=:uni");
//        q.setString("uni", cs);
//        List <MiniPojo>l=q.list();
//        for(MiniPojo pm:l)
//        {
//            cs_id=pm.getS_id();
//        }
//         Query q1=s.createQuery("select s from MiniPojo s where s.station=:nni");
//        q1.setString("nni", ds);
//        List <MiniPojo>l1=q1.list();
//        for(MiniPojo pm:l1)
//        {
//            d_id=pm.getS_id();
//        }
//        
//        List p=new ArrayList(1000);
//        p=Calculate.distance(cs_id,d_id);
//        
//        new CollegeProject(p).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calculateAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String cs=jTextField1.getText();
        String ds=jTextField2.getText();
        int cs_id=0;
        int d_id=0;
//        Configuration cfg=new Configuration();
//        cfg.configure("hibernate.cfg.xml");
//        SessionFactory sf=cfg.buildSessionFactory();
//        Session s=sf.openSession();
//        Query q=s.createQuery("select s from MiniPojo s where s.station=:uni");
//        q.setString("uni", cs);
//        List <MiniPojo>l=q.list();
//        for(MiniPojo pm:l)
//        {
//            cs_id=pm.getS_id();
//        }
//         Query q1=s.createQuery("select s from MiniPojo s where s.station=:nni");
//        q1.setString("nni", ds);
//        List <MiniPojo>l1=q1.list();
//        for(MiniPojo pm:l1)
//        {
//            d_id=pm.getS_id();
//        }
//        List p=new ArrayList(1000);
//        p=Calculate.distance(cs_id,d_id);
//        int count=0;
//        Iterator i=p.iterator();
//        while(i.hasNext())
//        {
//            System.out.println(i.next()+"");
//            count++;
//        }
//        int no_of_stations=count;
//         String f=Integer.toString(no_of_stations);
//         jTextField3.setText(f);
//         
//        int rupees=0;
//        if(count==2)
//        {
//             rupees=9;
//        }
//        else
//        {
//            rupees=9+(count-1);
//        }
//        
        jTextField4.setText(Integer.toString(rupees)+" "+"rs");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void alternateRouteAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cs=jTextField1.getText();
        String ds=jTextField2.getText();
        int cs_id=0;
        int d_id=0;
//        Configuration cfg=new Configuration();
//        cfg.configure("hibernate.cfg.xml");
//        SessionFactory sf=cfg.buildSessionFactory();
//        Session s=sf.openSession();
//        Query q=s.createQuery("select s from MiniPojo s where s.station=:uni");
//        q.setString("uni", cs);
//        List <MiniPojo>l=q.list();
//        for(MiniPojo pm:l)
//        {
//            cs_id=pm.getS_id();
//        }
//         Query q1=s.createQuery("select s from MiniPojo s where s.station=:nni");
//        q1.setString("nni", ds);
//        List <MiniPojo>l1=q1.list();
//        for(MiniPojo pm:l1)
//        {
//            d_id=pm.getS_id();
//        }
//        
//        List p=new ArrayList(1000);
//        p=Calculate2.distance2(cs_id,d_id);
//        
//        new CollegeProject2(p).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetroHome().setVisible(true);
            }
        });
    }

    
}
